
server:
  port: 8098
global:
  datasource: rct=RCT随机对照试验, meta=META分析
spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: file:src/main/resources/templates/
    encoding: UTF-8
    mode: HTML5
# wkhtmltopdf command路径
wkhtmltopdfCommandpath: "C:\\wkhtmltox-0.12.6-1.mxe-cross-win64\\wkhtmltox\\bin\\wkhtmltopdf.exe"